name = "visit-counter"
main = "workers/visit-counter.js"
compatibility_date = "2025-11-06"
kv_namespaces = [
  { binding = "PYTHIA_TOP50_KV", id = "[YOUR_KV_ID]" }
]
routes = [
  { pattern = "p-score.me/api/visits", zone_name = "p-score.me" }
]
